# Generated by Django 4.2.16 on 2024-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(max_length=50, verbose_name='Название Клуба')),
                ('NewsName', models.CharField(max_length=50, verbose_name='Название Новости')),
                ('Anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('TextNews', models.TextField(verbose_name='Статья')),
                ('Date', models.DateTimeField(verbose_name='Дата события')),
                ('Date_Stop', models.DateTimeField(verbose_name='Закрытие регистрации')),
                ('ImgNews', models.ImageField(blank=True, upload_to='main/image', verbose_name='Картинка Новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
