# Generated by Django 4.2.16 on 2024-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ImgNews',
            field=models.ImageField(blank=True, upload_to='it_startup/main/static/image/post', verbose_name='Картинка Новости'),
        ),
    ]
