# Generated by Django 4.2.16 on 2024-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_imgnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ImgNews',
            field=models.ImageField(blank=True, upload_to='it_startup/main/static/main/post', verbose_name='Картинка Новости'),
        ),
    ]
