# Generated by Django 4.2.16 on 2024-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='Number',
            field=models.CharField(max_length=20, verbose_name='Номер Телефона'),
        ),
    ]
