# Generated by Django 4.2.16 on 2024-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_articles_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='University',
            field=models.CharField(blank=True, max_length=50, verbose_name='Университет'),
        ),
    ]
